version: '3.7'
services:
  postgres:
    image: postgres:16
    container_name: db_app_dev
    env_file:
      - /envs/.env-develop
    environment:
      POSTGRES_DB: sales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432

  postgres_test:
    image: postgres:16
    container_name: test_db_app_dev
    env_file:
      - /envs/.env-develop
    environment:
      POSTGRES_DB: sales_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - 5433:5432

  sales:
    image: sales_image
    build:
      context: .
    container_name: sales_app_dev
    env_file:
      - /envs/.env-develop
    depends_on:
      - postgres
      - postgres_test
    command: ["/dns_test_task/docker_scripts/app.sh"]
    ports:
      - 5000:5000 
