version: '3.7'
services:
  db:
    image: postgres:16
    container_name: db_app
    env_file:
      - .env-prod
    ports:
      - 5432:5432

  sales:
    image: sales_image
    build:
      context: .
    container_name: sales_app
    env_file:
      - .env-prod
    depends_on:
      - db
    command: ["/dns_test_task/docker/app.sh"]
    ports:
      - 5000:5000 

